on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Local cache
      uses: actions/cache@v5
      with:
        path: /nix/store
        key: "${{ runner.os }}-nix-cache"
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    # follow guide: https://nix.dev/tutorials/continuous-integration-github-actions
    # this uses the tokens which are revokable
    - uses: cachix/cachix-action@v15
      with:
        name: jappie
        # If you chose API tokens for write access OR if you have a private cache
        # authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
    - run: nix-shell --run "echo OK"
